name: Python Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint greeter/greet.py test_greet.py

      - name: Run tests
        run: python -m unittest discover


      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Workflow Failed
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          body: |
            The workflow has failed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}

            View the workflow:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

